<?xml version="1.0" encoding="utf-8"?>

<!--
  Description of the ROSelito robot.

  Author: Helio Perroni Filho
-->

<robot name="roselito" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find roselito_description)/urdf/ugv02.xacro"/>

  <xacro:property name="payload_base_length" value="${156.22 * M}"/>
  <xacro:property name="payload_base_width" value="${159.96 * M}"/>
  <xacro:property name="payload_base_height" value="${42.7 * M}"/>

  <xacro:property name="lidar_side" value="${45.61 * M}"/>
  <xacro:property name="lidar_height" value="${37.6 * M}"/>

  <xacro:solid_block
    name="payload_base"
    size_x="${payload_base_length}"
    size_y="${payload_base_width}"
    size_z="${payload_base_height}"
  />

  <xacro:joint_fixed
    parent="body"
    child="payload_base"
    z="${0.5 * (body_height + payload_base_height)}"
  />

  <link name="camera_front"/>
  <xacro:joint_fixed
    parent="payload_base"
    child="camera_front"
    x="${0.5 * payload_base_length}"
  />

  <xacro:solid_block
    name="lidar"
    size_x="${lidar_side}"
    size_y="${lidar_side}"
    size_z="${lidar_height}"
  />

  <xacro:joint_fixed
    parent="payload_base"
    child="lidar"
    x="${0.5 * payload_base_height}"
    z="${0.5 * (payload_base_height + lidar_height)}"
  />

  <link name="laser"/>
  <xacro:joint_fixed
    parent="lidar"
    child="laser"
    z="${0.5 * lidar_height}"
  />
</robot>
